### ISSUE TITLE
Modo escuro muda a cor das letras das tabelas para branco

### ISSUE THREAD

**Issue by rtheodoro** [curso-r/programando-em-shiny#1]
Boa tarde!

Estava dando uma olhada no livro em modo escuro e quando vi a tabela, ela ficou toda branca.
No modo claro funciona normal.

Link: http://programando-em-shiny.curso-r.com/add-interatividade.html
![Captura de tela de 2022-10-06 16-50-07](https://user-images.githubusercontent.com/36709613/194405832-0d2860c6-a011-49eb-9907-2f2840a01c9a.png)

**Comment by williamorim** [comment]
Obrigado por relatar o problema @rtheodoro 

Troquei o `background-color` das tabelas para `transparent`. Agora o texto das tabelas fica visível no modo escuro.
