### ISSUE TITLE
Link de referência quebrado

### ISSUE THREAD

**Issue by rtheodoro** [curso-r/programando-em-shiny#2]
Link:
http://programando-em-shiny.curso-r.com/reatividade-conceitos.html

Trecho com a referência quebrada:
"No restante deste capítulo, aprenderemos alguns conceitos e funções que nos permitirão ter um controle maior sobre a reatividade no Shiny. Não esgotaremos o assunto reatividade aqui, ele será retomado no [Capítulo 7](http://programando-em-shiny.curso-r.com/reatividade-mais-pecas.html) e no [Capítulo -sec-reatividade3], mas já sairemos capazes de construir diversos tipos de interação entre inputs e outputs em nossos apps."

Acredito que a referência correta seja http://programando-em-shiny.curso-r.com/reatividade-problemas-complexos.html

EDIT----

No final existe outra referência quebrada
"Falaremos mais de outros valores reativos e observers no [Capítulo -sec-reatividade2]."

**Comment by williamorim** [comment]
Obrigado @rtheodoro 
Corrigi as referências.
