### ISSUE TITLE
Erro de digitação em código

### ISSUE THREAD

**Issue by rtheodoro** [curso-r/programando-em-shiny#3]
Na página http://programando-em-shiny.curso-r.com/reatividade-conceitos.html, tem os dois exemplos de código abaixo.

Acredito que eles estejam com um parenteses fechando a mais em `hist(input$variavel))`

```r
server <- function(input, output, session) {
  output$hist <- renderPlot({
    hist(input$variavel))
  }) 
}
```

```r
server <- function(input, output, session) {
  output$hist <- hist(input$variavel))
}
```

EDIT ----

Mais abaixo tem também problemas na referência:

"Para evitar esses problemas, que discutiremos com mais detalhes no [Capítulo 7](http://programando-em-shiny.curso-r.com/reatividade-mais-pecas.html) e no [Capítulo -sec-reatividade3], podemos"

**Comment by williamorim** [comment]
Obrigado @rtheodoro 

Corrigi os erros.
